<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetCoreVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Touki.Resources.Generator.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>

    <!-- Not a security boundary, the strong name is for identity and ease of use from other signed assemblies. -->
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\klutzyninja.snk</AssemblyOriginatorKeyFile>

    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator"
                      GeneratePathProperty="true"
                      PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestFramework" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageDownload Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="[1.0.3]" />

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ResxSourceGeneratorPackagePath</_Parameter1>
      <_Parameter2>$(PkgMicrosoft_CodeAnalysis_ResxSourceGenerator)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NuGetPackageRoot</_Parameter1>
      <_Parameter2>$(NuGetPackageRoot)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\touki.resources.generator\touki.resources.generator.csproj" />
    <ProjectReference Include="..\..\touki\touki.csproj"
                      AdditionalProperties="TargetFramework=$(DotNetCoreVersion)"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>