// Copyright (c) 2025 Jeremy W Kuhne
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license information

namespace Touki.Analyzers;

[TestClass]
public class UseIsNullAnalyzerTests
{
    [TestMethod]
    public async Task AnalyzeComparison_EqualsNull_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => value == null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(UseIsNullAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeComparison_NotEqualsNull_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => value != null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(UseIsNullAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeComparison_NullOnLeft_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => null == value;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(UseIsNullAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeComparison_NotEqualsNullOnLeft_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => null != value;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(UseIsNullAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeComparison_EqualsNull_ReportsAtOperatorToken()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => value == null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle();
        Location location = diagnostics[0].Location;
        location.SourceTree!.GetText().ToString(location.SourceSpan).Should().Be("==");
    }

    [TestMethod]
    public async Task AnalyzeComparison_IsNullPattern_ReportsNoDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(object value) => value is null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeComparison_NonNullEquality_ReportsNoDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Check(int value) => value == 0;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeComparison_GeneratedCode_ReportsNoDiagnostic()
    {
        // The leading '<auto-generated/>' comment marks the whole tree as generated code, which
        // ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None) excludes from analysis.
        const string source = """
            // <auto-generated/>
            class Sample
            {
                bool Check(object value) => value == null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics =
            await AnalyzerTestHarness.GetDiagnosticsAsync(new UseIsNullAnalyzer(), source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }
}
