// Copyright (c) 2025 Jeremy W Kuhne
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license information

namespace Touki.Analyzers;

[TestClass]
public class AvoidNullForgivingOperatorAnalyzerTests
{
    private static readonly IReadOnlyDictionary<string, ReportDiagnostic> s_diagnosticOptions =
        new Dictionary<string, ReportDiagnostic>
        {
            [AvoidNullForgivingOperatorAnalyzer.DiagnosticId] = ReportDiagnostic.Warn,
        };

    [TestMethod]
    public async Task AnalyzeSuppression_Identifier_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                string Get(string? value) => value!;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(AvoidNullForgivingOperatorAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeSuppression_NullLiteral_ReportsDiagnostic()
    {
        const string source = """
            class Sample
            {
                object Value { get; } = null!;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be(AvoidNullForgivingOperatorAnalyzer.DiagnosticId);
    }

    [TestMethod]
    public async Task AnalyzeSuppression_ReportsAtOperatorToken()
    {
        const string source = """
            class Sample
            {
                string Get(string? value) => value!;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().ContainSingle();
        Location location = diagnostics[0].Location;
        SyntaxTree? sourceTree = location.SourceTree;
        sourceTree.Should().NotBeNull();

        if (sourceTree is null)
        {
            return;
        }

        sourceTree.GetText().ToString(location.SourceSpan).Should().Be("!");
    }

    [TestMethod]
    public async Task AnalyzeSuppression_RuleNotEnabled_ReportsNoDiagnostic()
    {
        const string source = """
            class Sample
            {
                string Get(string? value) => value!;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzerTestHarness.GetDiagnosticsAsync(
            new AvoidNullForgivingOperatorAnalyzer(),
            source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeSuppression_LogicalNegation_ReportsNoDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool Invert(bool value) => !value;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeSuppression_NotEquals_ReportsNoDiagnostic()
    {
        const string source = """
            class Sample
            {
                bool HasValue(object? value) => value != null;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeSuppression_GeneratedCode_ReportsNoDiagnostic()
    {
        const string source = """
            // <auto-generated/>
            class Sample
            {
                string Get(string? value) => value!;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await GetDiagnosticsAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    private static Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source)
        => AnalyzerTestHarness.GetDiagnosticsAsync(
            new AvoidNullForgivingOperatorAnalyzer(),
            source,
            diagnosticOptions: s_diagnosticOptions);
}
