// Copyright (c) 2025 Jeremy W Kuhne
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license information

using Microsoft.CodeAnalysis.CSharp;

namespace Touki.Analyzers;

public partial class MemberXmlDocumentationAnalyzerTests
{
    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedNamespacedEnumValue_InheritsSummary()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                namespace Windows.Win32.Graphics.DirectWrite;

                public enum DWRITE_FONT_FEATURE_TAG
                {
                    /// <summary>
                    ///  <para>The stylistic set 17 feature.</para>
                    /// </summary>
                    DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_17
                }
                """,
                "DWRITE_FONT_FEATURE_TAG.g.cs"),
            (
                """
                using Windows.Win32.Graphics.DirectWrite;

                namespace Consumer;

                public enum FontFeatureTag
                {
                    /// <inheritdoc cref="DWRITE_FONT_FEATURE_TAG.DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_17"/>
                    StylisticSet17
                }
                """,
                "FontFeatureTag.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedMethodWithRenamedParameter_ReportsParameter()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                namespace Generated.Subnamespace;

                [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
                public static class GeneratedApi
                {
                    /// <summary><para>Transforms a value.</para></summary>
                    /// <param name="value">The input.</param>
                    /// <returns>The transformed value.</returns>
                    public static int Transform(int value) => value;
                }
                """,
                "GeneratedApi.cs"),
            (
                """
                using Generated.Subnamespace;

                namespace Consumer;

                public static class Sample
                {
                    /// <inheritdoc cref="GeneratedApi.Transform(int)"/>
                    public static int Transform(int input) => input;
                }
                """,
                "Sample.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
        diagnostic.GetMessage().Should().Contain("'input'");
    }

    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedMethodWithSummaryOnly_ReportsMissingParametersAndReturns()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                namespace Generated;

                public static class GeneratedApi
                {
                    /// <summary><para>Transforms a value.</para></summary>
                    public static int Transform(int value) => value;
                }
                """,
                "GeneratedApi.g.cs"),
            (
                """
                public static class Sample
                {
                    /// <inheritdoc cref="Generated.GeneratedApi.Transform(int)"/>
                    public static int Transform(int value) => value;
                }
                """,
                "Sample.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().ContainSingle(diagnostic => IsParameterDocumentationDiagnostic(diagnostic));
        diagnostics.Should().ContainSingle(diagnostic => IsReturnDocumentationDiagnostic(diagnostic));
    }

    [TestMethod]
    public async Task AnalyzeMember_BareInheritdocFromGeneratedOverride_InheritsSummary()
    {
        const string source = """
            [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
            public abstract class GeneratedBase
            {
                /// <summary>Runs the operation.</summary>
                public abstract void Run();
            }

            public sealed class Sample : GeneratedBase
            {
                /// <inheritdoc/>
                public override void Run() { }
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_BareInheritdocFromGeneratedInterface_InheritsParameterAndReturnDocumentation()
    {
        const string source = """
            namespace Generated;

            [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
            public interface IService
            {
                /// <summary>Transforms a value.</summary>
                /// <param name="value">The input.</param>
                /// <returns>The transformed value.</returns>
                int Transform(int value);
            }

            public sealed class Service : IService
            {
                /// <inheritdoc/>
                public int Transform(int value) => value;
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedProjectEnumValue_InheritsSummary()
    {
        SyntaxTree generatedTree = CSharpSyntaxTree.ParseText(
            """
            namespace Generated.Subnamespace;

            public enum GeneratedTags
            {
                /// <summary>The feature tag.</summary>
                Feature
            }
            """,
            path: "GeneratedTags.g.cs");
        CSharpCompilation generatedCompilation =
            CSharpCompilation.Create(
                "GeneratedTagsProject",
                syntaxTrees: [generatedTree],
                references: RoslynTestEnvironment.References,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        const string source = """
            public enum FeatureTag
            {
                /// <inheritdoc cref="Generated.Subnamespace.GeneratedTags.Feature"/>
                Feature
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzerTestHarness.GetDiagnosticsAsync(
            new MemberXmlDocumentationAnalyzer(),
            source,
            additionalReferences: [generatedCompilation.ToMetadataReference()]).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefChainThroughGeneratedEnumValues_InheritsSummary()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                public enum GeneratedTags
                {
                    /// <summary>The feature tag.</summary>
                    Feature,

                    /// <inheritdoc cref="Feature"/>
                    Alias
                }
                """,
                "GeneratedTags.g.cs"),
            (
                """
                public enum FeatureTag
                {
                    /// <inheritdoc cref="GeneratedTags.Alias"/>
                    Feature
                }
                """,
                "FeatureTag.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    [DataRow("/// <remarks>No top-level summary.</remarks>")]
    [DataRow("/// <summary><para>Malformed summary.</summary>")]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedIncompleteEnumValue_ReportsMember(string targetDocumentation)
    {
        string generated = $$"""
            // <auto-generated/>
            public enum GeneratedTags
            {
                {{targetDocumentation}}
                Feature
            }
            """;
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (generated, "GeneratedTags.g.cs"),
            (
                """
                public enum FeatureTag
                {
                    /// <inheritdoc cref="GeneratedTags.Feature"/>
                    Feature
                }
                """,
                "FeatureTag.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        diagnostic.GetMessage().Should().Contain("<inheritdoc> does not resolve to a top-level <summary>");
        diagnostic.Location.GetRequiredSourceTree().FilePath.Should().Be("FeatureTag.cs");
    }

    [TestMethod]
    [DataRow("/// <remarks>The coordinate may be < 0.</remarks>", true)]
    [DataRow("/// <remarks>The coordinate may be &lt; 0.</remarks>", false)]
    public async Task AnalyzeMember_GeneratedEnumSummaryFollowedByMalformedRemarks_RequiresValidXml(
        string remarks,
        bool expectWarning)
    {
        string generated = $$"""
            // <auto-generated/>
            public enum NativeMessage
            {
                /// <summary>Left mouse button pressed.</summary>
                {{remarks}}
                WM_LBUTTONDOWN
            }
            """;
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (generated, "NativeMessage.g.cs"),
            (
                """
                public enum MessageType
                {
                    /// <inheritdoc cref="NativeMessage.WM_LBUTTONDOWN"/>
                    LeftButtonDown
                }
                """,
                "MessageType.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        if (expectWarning)
        {
            Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
            diagnostic.GetMessage().Should().Contain("<inheritdoc> does not resolve to a top-level <summary>");
        }
        else
        {
            diagnostics.Should().BeEmpty();
        }
    }

    [TestMethod]
    public async Task AnalyzeMember_ExplicitCrefToGeneratedUndocumentedMethod_ReportsAllRequirements()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                public static class GeneratedApi
                {
                    /// <remarks>Does not document the method.</remarks>
                    public static int Transform(int value) => value;
                }
                """,
                "GeneratedApi.g.cs"),
            (
                """
                public static class Sample
                {
                    /// <inheritdoc cref="GeneratedApi.Transform(int)"/>
                    public static int Transform(int input) => input;
                }
                """,
                "Sample.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().HaveCount(3);
        diagnostics.Should().ContainSingle(
            diagnostic => diagnostic.GetMessage().Contains(
                "<inheritdoc> does not resolve to a top-level <summary>",
                StringComparison.Ordinal));
        diagnostics.Should().ContainSingle(diagnostic => IsParameterDocumentationDiagnostic(diagnostic));
        diagnostics.Should().ContainSingle(diagnostic => IsReturnDocumentationDiagnostic(diagnostic));
    }
}
