// Copyright (c) 2025 Jeremy W Kuhne
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license information

using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Touki.Analyzers;

public partial class MemberXmlDocumentationAnalyzerTests
{
    private const string GeneratedGraphicsModeSource = """
        // <auto-generated/>
        namespace Generated;

        public readonly struct Hdc { }
        public enum GraphicsMode { Compatible }
        public interface IContext { Hdc Handle { get; } }

        public static class Interop
        {
            /// <summary><para>Gets the graphics mode.</para></summary>
            /// <param name="hdc">The device context handle.</param>
            /// <returns>The graphics mode identifier.</returns>
            public static int GetGraphicsMode(Hdc hdc) => 0;
        }
        """;

    private const string GeneratedComStructSource = """
        // <auto-generated/>
        namespace Generated;

        public readonly struct IFileDialogEvents
        {
            /// <summary>Handles a file dialog confirmation.</summary>
            /// <param name="dialog">The file dialog.</param>
            /// <returns>The result.</returns>
            public int OnFileOk(int dialog) => 0;
        }

        public readonly struct ID2D1RenderTarget
        {
            /// <summary>Draws the text layout.</summary>
            /// <param name="origin">The origin.</param>
            /// <param name="layout">The layout.</param>
            public void DrawTextLayout(int origin, string layout) { }
        }
        """;

    private const string GeneratedDialogEventOverloadsSource = """
        // <auto-generated/>
        namespace Generated;

        public readonly unsafe struct IFileDialogEvents
        {
            /// <summary>Handles an overwrite.</summary>
            /// <param name="response">The response pointer.</param>
            /// <returns>The result.</returns>
            public int OnOverwrite(int* response) => 0;

            /// <inheritdoc cref="OnOverwrite(int*)"/>
            public int OnOverwrite(out int response)
            {
                response = 0;
                return 0;
            }
        }
        """;

    private static CompilationReference CreateGeneratedMetadataAliasReference(MetadataReference reference) =>
        CreateCompilationReference(
            """
            [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
            public static class GeneratedApi
            {
                /// <inheritdoc cref="External.Get(int)"/>
                public static int Get(int value) => External.Get(value);
            }
            """,
            assemblyName: "GeneratedMetadataAlias",
            additionalReferences: [reference]);

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedMethodWithDifferentParameterAndReturnType_ReportsBoth()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedGraphicsModeSource, "Interop.g.cs"),
            (
                """
                using Generated;

                public static class ContextExtensions
                {
                    /// <inheritdoc cref="Generated.Interop.GetGraphicsMode(Generated.Hdc)"/>
                    public static GraphicsMode GetGraphicsMode<T>(this T context) where T : IContext =>
                        (GraphicsMode)Interop.GetGraphicsMode(context.Handle);
                }
                """,
                "ContextExtensions.cs")
        ];

        SyntaxTree generatedTree = CSharpSyntaxTree.ParseText(sources[0].Source, path: sources[0].FileName);
        SyntaxTree wrapperTree = CSharpSyntaxTree.ParseText(sources[1].Source, path: sources[1].FileName);
        CSharpCompilation compilation = CSharpCompilation.Create(
            "GraphicsModeCref",
            syntaxTrees: [generatedTree, wrapperTree],
            references: RoslynTestEnvironment.References,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        XmlCrefAttributeSyntax cref = wrapperTree.GetRoot().DescendantNodes(descendIntoTrivia: true)
            .OfType<XmlCrefAttributeSyntax>().Single();
        SymbolInfo target = compilation.GetSemanticModel(wrapperTree).GetSymbolInfo(cref.Cref);
        target.Symbol.Should().BeAssignableTo<IMethodSymbol>();

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().ContainSingle(diagnostic => IsParameterDocumentationDiagnostic(diagnostic));
        diagnostics.Should().ContainSingle(diagnostic => IsReturnDocumentationDiagnostic(diagnostic));
        diagnostics.Should().OnlyContain(diagnostic => diagnostic.Location.GetRequiredSourceTree().FilePath == "ContextExtensions.cs");
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedMethodWithMatchingSignature_InheritsParameterAndReturnDocumentation()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedGraphicsModeSource, "Interop.g.cs"),
            (
                """
                using Generated;

                public static class ContextExtensions
                {
                    /// <inheritdoc cref="Generated.Interop.GetGraphicsMode(Generated.Hdc)"/>
                    public static int GetGraphicsMode(Hdc hdc) => Interop.GetGraphicsMode(hdc);
                }
                """,
                "ContextExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedStructMethod_InheritsMatchingParameterAndReturnDocumentation()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedComStructSource, "ComStructs.g.cs"),
            (
                """
                public static class FileDialogEvents
                {
                    /// <inheritdoc cref="Generated.IFileDialogEvents.OnFileOk(int)"/>
                    public static int OnFileOk(int dialog) => 0;
                }
                """,
                "FileDialogEvents.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedStructMethodWithExtensionReceiver_InheritsNamedParameters()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedComStructSource, "ComStructs.g.cs"),
            (
                """
                public static class RenderTargetExtensions
                {
                    /// <inheritdoc cref="Generated.ID2D1RenderTarget.DrawTextLayout(int, string)"/>
                    /// <param name="target">The render target.</param>
                    public static void DrawTextLayout(
                        this Generated.ID2D1RenderTarget target,
                        int origin,
                        string layout) => target.DrawTextLayout(origin, layout);
                }
                """,
                "RenderTargetExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedStructMethodWithoutReceiverTag_ReportsReceiverOnly()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedComStructSource, "ComStructs.g.cs"),
            (
                """
                public static class RenderTargetExtensions
                {
                    /// <inheritdoc cref="Generated.ID2D1RenderTarget.DrawTextLayout(int, string)"/>
                    public static void DrawTextLayout(
                        this Generated.ID2D1RenderTarget target,
                        int origin,
                        string layout) => target.DrawTextLayout(origin, layout);
                }
                """,
                "RenderTargetExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
        diagnostic.GetMessage().Should().Contain("'target'");
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedRawPointerOverload_InheritsSignatureDocumentation()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedDialogEventOverloadsSource, "IFileDialogEvents.g.cs"),
            (
                """
                public static unsafe class FileDialogEvents
                {
                    /// <inheritdoc cref="Generated.IFileDialogEvents.OnOverwrite(int*)"/>
                    public static int OnOverwrite(int* response) => 0;
                }
                """,
                "FileDialogEvents.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedOutOverload_TraversesSummaryButRequiresLocalParameterDoc()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedDialogEventOverloadsSource, "IFileDialogEvents.g.cs"),
            (
                """
                public static class FileDialogEvents
                {
                    /// <inheritdoc cref="Generated.IFileDialogEvents.OnOverwrite(out int)"/>
                    public static int OnOverwrite(out int response)
                    {
                        response = 0;
                        return 0;
                    }
                }
                """,
                "FileDialogEvents.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
        diagnostic.GetMessage().Should().Contain("'response'");
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedMethodWithDifferentParameterType_ReportsParameterOnly()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedGraphicsModeSource, "Interop.g.cs"),
            (
                """
                using Generated;

                public static class ContextExtensions
                {
                    /// <inheritdoc cref="Generated.Interop.GetGraphicsMode(Generated.Hdc)"/>
                    public static int GetGraphicsMode(object hdc) => Interop.GetGraphicsMode((Hdc)hdc);
                }
                """,
                "ContextExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefToGeneratedMethodWithDifferentReturnType_ReportsReturnOnly()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedGraphicsModeSource, "Interop.g.cs"),
            (
                """
                using Generated;

                public static class ContextExtensions
                {
                    /// <inheritdoc cref="Generated.Interop.GetGraphicsMode(Generated.Hdc)"/>
                    public static GraphicsMode GetGraphicsMode(Hdc hdc) =>
                        (GraphicsMode)Interop.GetGraphicsMode(hdc);
                }
                """,
                "ContextExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsReturnDocumentationDiagnostic(diagnostic).Should().BeTrue();
    }

    [TestMethod]
    public async Task AnalyzeMember_LocalSignatureTagsOverrideIncompatibleGeneratedCref_ReportsNothing()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (GeneratedGraphicsModeSource, "Interop.g.cs"),
            (
                """
                using Generated;

                public static class ContextExtensions
                {
                    /// <inheritdoc cref="Generated.Interop.GetGraphicsMode(Generated.Hdc)"/>
                    /// <param name="context">The context to read.</param>
                    /// <returns>The graphics mode.</returns>
                    public static GraphicsMode GetGraphicsMode<T>(this T context) where T : IContext =>
                        (GraphicsMode)Interop.GetGraphicsMode(context.Handle);
                }
                """,
                "ContextExtensions.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefThroughGeneratedMethodToMetadata_InheritsMatchingSignatureTags()
    {
        MetadataReference reference = CreateMetadataReference(
            "public static class External { public static int Get(int value) => value; }",
            new Dictionary<string, string>
            {
                ["M:External.Get(System.Int32)"] =
                    "<member><summary>Gets a value.</summary><param name=\"value\">The value.</param>"
                    + "<returns>The value.</returns></member>"
            });
        CompilationReference generatedReference = CreateGeneratedMetadataAliasReference(reference);
        const string source = """
            public static class Sample
            {
                /// <inheritdoc cref="GeneratedApi.Get(int)"/>
                public static int Get(int value) => GeneratedApi.Get(value);
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzerTestHarness.GetDiagnosticsAsync(
            new MemberXmlDocumentationAnalyzer(),
            source,
            additionalReferences: [reference, generatedReference]).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefThroughGeneratedMethodToMetadataWithoutSignatureTags_ReportsBoth()
    {
        MetadataReference reference = CreateMetadataReference(
            "public static class External { public static int Get(int value) => value; }",
            new Dictionary<string, string>
            {
                ["M:External.Get(System.Int32)"] = "<member><summary>Gets a value.</summary></member>"
            });
        CompilationReference generatedReference = CreateGeneratedMetadataAliasReference(reference);
        const string source = """
            public static class Sample
            {
                /// <inheritdoc cref="GeneratedApi.Get(int)"/>
                public static int Get(int value) => GeneratedApi.Get(value);
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzerTestHarness.GetDiagnosticsAsync(
            new MemberXmlDocumentationAnalyzer(),
            source,
            additionalReferences: [reference, generatedReference]).ConfigureAwait(false);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().ContainSingle(diagnostic => IsParameterDocumentationDiagnostic(diagnostic));
        diagnostics.Should().ContainSingle(diagnostic => IsReturnDocumentationDiagnostic(diagnostic));
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefThroughGeneratedMethodToMetadataWithNestedSignatureTags_ReportsBoth()
    {
        MetadataReference reference = CreateMetadataReference(
            "public static class External { public static int Get(int value) => value; }",
            new Dictionary<string, string>
            {
                ["M:External.Get(System.Int32)"] =
                    "<member><summary>Gets a value.</summary><remarks><param name=\"value\">The value.</param>"
                    + "<returns>The value.</returns></remarks></member>"
            });
        CompilationReference generatedReference = CreateGeneratedMetadataAliasReference(reference);
        const string source = """
            public static class Sample
            {
                /// <inheritdoc cref="GeneratedApi.Get(int)"/>
                public static int Get(int value) => GeneratedApi.Get(value);
            }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzerTestHarness.GetDiagnosticsAsync(
            new MemberXmlDocumentationAnalyzer(),
            source,
            additionalReferences: [reference, generatedReference]).ConfigureAwait(false);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().ContainSingle(diagnostic => IsParameterDocumentationDiagnostic(diagnostic));
        diagnostics.Should().ContainSingle(diagnostic => IsReturnDocumentationDiagnostic(diagnostic));
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefThroughGeneratedMethodChain_InheritsMatchingSignatureTags()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                public static class GeneratedApi
                {
                    /// <summary>Transforms the value.</summary>
                    /// <param name="value">The value.</param>
                    /// <returns>The transformed value.</returns>
                    public static int Root(int value) => value;

                    /// <inheritdoc cref="Root(int)"/>
                    public static int Alias(int value) => Root(value);
                }
                """,
                "GeneratedApi.g.cs"),
            (
                """
                public static class Sample
                {
                    /// <inheritdoc cref="GeneratedApi.Alias(int)"/>
                    public static int Get(int value) => GeneratedApi.Alias(value);
                }
                """,
                "Sample.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task AnalyzeMember_CrefThroughGeneratedMethodWithRenamedIntermediate_ReportsParameterOnly()
    {
        IReadOnlyList<(string Source, string FileName)> sources =
        [
            (
                """
                // <auto-generated/>
                public static class GeneratedApi
                {
                    /// <summary>Transforms the value.</summary>
                    /// <param name="value">The value.</param>
                    /// <returns>The transformed value.</returns>
                    public static int Root(int value) => value;

                    /// <inheritdoc cref="Root(int)"/>
                    public static int Alias(int other) => Root(other);
                }
                """,
                "GeneratedApi.g.cs"),
            (
                """
                public static class Sample
                {
                    /// <inheritdoc cref="GeneratedApi.Alias(int)"/>
                    public static int Get(int value) => GeneratedApi.Alias(value);
                }
                """,
                "Sample.cs")
        ];

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(sources).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
    }

    [TestMethod]
    public async Task AnalyzeMember_PrimaryConstructorInheritingGeneratedTypeWithoutParameterDoc_ReportsParameter()
    {
        const string source = """
            [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
            public class Base { }

            /// <inheritdoc/>
            public class Derived(int value) : Base { }
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source).ConfigureAwait(false);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        IsParameterDocumentationDiagnostic(diagnostic).Should().BeTrue();
    }

    [TestMethod]
    public async Task AnalyzeMember_PrimaryConstructorInheritingGeneratedRecordParameterDoc_ReportsNothing()
    {
        const string source = """
            /// <summary>A base record.</summary>
            /// <param name="Value">The value.</param>
            [System.CodeDom.Compiler.GeneratedCode("test", "1.0")]
            public record BaseRecord(int Value);

            /// <inheritdoc/>
            public record DerivedRecord(int Value) : BaseRecord(Value);
            """;

        ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source).ConfigureAwait(false);

        diagnostics.Should().BeEmpty();
    }
}
